# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-dd88751d-fd64-41d3-a5e0-ba9e912fd7f8";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-dd88751d-fd64-41d3-a5e0-ba9e912fd7f8".device = "/dev/disk/by-uuid/dd88751d-fd64-41d3-a5e0-ba9e912fd7f8";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CE21-EFB7";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
